
package org.drip.execution.optimum;

/*
 * -*- mode: java; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*-
 */

/*!
 * Copyright (C) 2016 Lakshmi Krishnamurthy
 * 
 *  This file is part of DRIP, a free-software/open-source library for fixed income analysts and developers -
 * 		http://www.credit-trader.org/Begin.html
 * 
 *  DRIP is a free, full featured, fixed income rates, credit, and FX analytics library with a focus towards
 *  	pricing/valuation, risk, and market making.
 * 
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *   	you may not use this file except in compliance with the License.
 *   
 *  You may obtain a copy of the License at
 *  	http://www.apache.org/licenses/LICENSE-2.0
 *  
 *  Unless required by applicable law or agreed to in writing, software
 *  	distributed under the License is distributed on an "AS IS" BASIS,
 *  	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  
 *  See the License for the specific language governing permissions and
 *  	limitations under the License.
 */

/**
 * Almgren2003TradingTrajectory contains the Trading Trajectory generated by the Almgren (2003) Scheme under
 *  the Criterion of No-Drift. The References are:
 * 
 * 	- Almgren, R., and N. Chriss (1999): Value under Liquidation, Risk 12 (12).
 * 
 * 	- Almgren, R., and N. Chriss (2000): Optimal Execution of Portfolio Transactions, Journal of Risk 3 (2)
 * 		5-39.
 * 
 * 	- Almgren, R. (2003): Optimal Execution with Nonlinear Impact Functions and Trading-Enhanced Risk,
 * 		Applied Mathematical Finance 10 (1) 1-18.
 * 
 * 	- Almgren, R., and N. Chriss (2003): Bidding Principles, Risk 97-102.
 * 
 * 	- Bertsimas, D., and A. W. Lo (1998): Optimal Control of Execution Costs, Journal of Financial Markets,
 * 		1, 1-50.
 * 
 * @author Lakshmi Krishnamurthy
 */

public class Almgren2003TradingTrajectory extends org.drip.execution.optimum.ContinuousTradingTrajectory {
	private double _dblMaxExecutionTime = java.lang.Double.NaN;
	private double _dblHyperboloidBoundaryValue = java.lang.Double.NaN;

	/**
	 * Construct the Standard Almgren2003TradingTrajectory Instance
	 * 
	 * @param adblExecutionTimeNode Array containing the Trajectory Time Nodes
	 * @param dblTransactionCostExpectation The Expected Transaction Cost
	 * @param dblTransactionCostVariance The Variance of the Transaction Cost
	 * @param dblCharacteristicTime The Optimal Trajectory's "Characteristic" Time
	 * @param dblMaxExecutionTime The Optimal Trajectory's Maximal Execution Time (if it exists)
	 * @param dblHyperboloidBoundaryValue The Hyperboloid Boundary Value
	 * @param holdingsR1ToR1 The Optimal Trajectory R^1 To R^1 Holdings Function
	 * 
	 * @return The Standard Almgren2003TradingTrajectory Instance
	 */

	public static Almgren2003TradingTrajectory Standard (
		final double[] adblExecutionTimeNode,
		final double dblTransactionCostExpectation,
		final double dblTransactionCostVariance,
		final double dblCharacteristicTime,
		final double dblMaxExecutionTime,
		final double dblHyperboloidBoundaryValue,
		final org.drip.function.definition.R1ToR1 holdingsR1ToR1)
	{
		if (null == adblExecutionTimeNode || null == holdingsR1ToR1) return null;

		int iNumTimeNode = adblExecutionTimeNode.length;
		double[] adblHoldings = new double[iNumTimeNode];
		double[] adblTradeList = new double[iNumTimeNode - 1];

		if (2 >= iNumTimeNode) return null;

		for (int i = 0; i < iNumTimeNode; ++i) {
			try {
				adblHoldings[i] = holdingsR1ToR1.evaluate (adblExecutionTimeNode[i]);
			} catch (java.lang.Exception e) {
				e.printStackTrace();

				return null;
			}

			if (0 != i) adblTradeList[i - 1] = adblHoldings[i] - adblHoldings[i - 1];
		}

		try {
			return new Almgren2003TradingTrajectory (adblExecutionTimeNode, adblHoldings, adblTradeList,
				dblTransactionCostExpectation, dblTransactionCostVariance, dblCharacteristicTime,
					dblMaxExecutionTime, dblHyperboloidBoundaryValue, holdingsR1ToR1);
		} catch (java.lang.Exception e) {
			e.printStackTrace();
		}

		return null;
	}

	/**
	 * Almgren2003TradingTrajectory Constructor
	 * 
	 * @param adblExecutionTimeNode Array containing the Trajectory Time Nodes
	 * @param adblHoldings Array containing the Holdings
	 * @param adblTradeList Array containing the Trade List
	 * @param dblTransactionCostExpectation The Expected Transaction Cost
	 * @param dblTransactionCostVariance The Variance of the Transaction Cost
	 * @param dblCharacteristicTime The Optimal Trajectory's "Characteristic" Time
	 * @param dblMaxExecutionTime The Optimal Trajectory's Maximal Execution Time (if it exists)
	 * @param dblHyperboloidBoundaryValue The Hyperboloid Boundary Value
	 * @param holdingsR1ToR1 The Optimal Trajectory R^1 To R^1 Holdings Function
	 * 
	 * @throws java.lang.Exception Thrown if the Inputs are Invalid
	 */

	public Almgren2003TradingTrajectory (
		final double[] adblExecutionTimeNode,
		final double[] adblHoldings,
		final double[] adblTradeList,
		final double dblTransactionCostExpectation,
		final double dblTransactionCostVariance,
		final double dblCharacteristicTime,
		final double dblMaxExecutionTime,
		final double dblHyperboloidBoundaryValue,
		final org.drip.function.definition.R1ToR1 holdingsR1ToR1)
		throws java.lang.Exception
	{
		super (adblExecutionTimeNode, adblHoldings, adblTradeList, dblTransactionCostExpectation,
			dblTransactionCostVariance, dblCharacteristicTime, holdingsR1ToR1);

		if (!org.drip.quant.common.NumberUtil.IsValid (_dblHyperboloidBoundaryValue =
			dblHyperboloidBoundaryValue))
			throw new java.lang.Exception ("Almgren2003TradingTrajectory Constructor => Invalid Inputs");

		_dblMaxExecutionTime = dblMaxExecutionTime;
	}

	/**
	 * Retrieve the Optimal Trajectory Hyperboloid Boundary Value
	 * 
	 * @return The Optimal Trajectory Hyperboloid Boundary Value
	 */

	public double hyperboloidBoundaryValue()
	{
		return _dblHyperboloidBoundaryValue;
	}

	/**
	 * Retrieve the Optimal Trajectory Maximum Execution Time (if it exists)
	 * 
	 * @return The Optimal Trajectory Maximum Execution Time (if it exists)
	 */

	public double maxExecutionTime()
	{
		return _dblMaxExecutionTime;
	}
}
