
package org.drip.execution.optimum;

/*
 * -*- mode: java; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*-
 */

/*!
 * Copyright (C) 2016 Lakshmi Krishnamurthy
 * 
 *  This file is part of DRIP, a free-software/open-source library for fixed income analysts and developers -
 * 		http://www.credit-trader.org/Begin.html
 * 
 *  DRIP is a free, full featured, fixed income rates, credit, and FX analytics library with a focus towards
 *  	pricing/valuation, risk, and market making.
 * 
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *   	you may not use this file except in compliance with the License.
 *   
 *  You may obtain a copy of the License at
 *  	http://www.apache.org/licenses/LICENSE-2.0
 *  
 *  Unless required by applicable law or agreed to in writing, software
 *  	distributed under the License is distributed on an "AS IS" BASIS,
 *  	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  
 *  See the License for the specific language governing permissions and
 *  	limitations under the License.
 */

/**
 * Almgren2003PowerImpactContinuous contains the Trading Trajectory generated by the Almgren (2003) Power
 *  Impact Scheme under the Criterion of No-Drift. The References are:
 * 
 * 	- Almgren, R., and N. Chriss (1999): Value under Liquidation, Risk 12 (12).
 * 
 * 	- Almgren, R., and N. Chriss (2000): Optimal Execution of Portfolio Transactions, Journal of Risk 3 (2)
 * 		5-39.
 * 
 * 	- Almgren, R. (2003): Optimal Execution with Nonlinear Impact Functions and Trading-Enhanced Risk,
 * 		Applied Mathematical Finance 10 (1) 1-18.
 * 
 * 	- Almgren, R., and N. Chriss (2003): Bidding Principles, Risk 97-102.
 * 
 * 	- Bertsimas, D., and A. W. Lo (1998): Optimal Control of Execution Costs, Journal of Financial Markets,
 * 		1, 1-50.
 * 
 * @author Lakshmi Krishnamurthy
 */

public class Almgren2003PowerImpactContinuous extends
	org.drip.execution.optimum.EfficientContinuousTradingTrajectory {
	private double _dblExecutionTimeUpperBound = java.lang.Double.NaN;
	private double _dblHyperboloidBoundaryValue = java.lang.Double.NaN;

	/**
	 * Construct the Standard Almgren2003PowerImpactContinuous Instance
	 * 
	 * @param dblExecutionTime The Execution Time
	 * @param dblTransactionCostExpectation The Expected Transaction Cost
	 * @param dblTransactionCostVariance The Variance of the Transaction Cost
	 * @param dblCharacteristicTime The Optimal Trajectory's "Characteristic" Time
	 * @param dblExecutionTimeUpperBound The Optimal Trajectory's Execution Time Upper Bound (if it exists)
	 * @param dblHyperboloidBoundaryValue The Hyperboloid Boundary Value
	 * @param r1ToR1Holdings The Optimal Trajectory R^1 To R^1 Holdings Function
	 * 
	 * @return The Standard Almgren2003PowerImpactContinuous Instance
	 */

	public static Almgren2003PowerImpactContinuous Standard (
		final double dblExecutionTime,
		final double dblTransactionCostExpectation,
		final double dblTransactionCostVariance,
		final double dblCharacteristicTime,
		final double dblExecutionTimeUpperBound,
		final double dblHyperboloidBoundaryValue,
		final org.drip.function.definition.R1ToR1 r1ToR1Holdings)
	{
		if (null == r1ToR1Holdings) return null;

		try {
			org.drip.function.definition.R1ToR1 r1ToR1TradeRate = new org.drip.function.definition.R1ToR1
				(null) {
				@Override public double evaluate (
					final double dblVariate)
					throws java.lang.Exception
				{
					return r1ToR1Holdings.derivative (dblVariate, 1);
				}
			};

			return new Almgren2003PowerImpactContinuous (dblExecutionTime, dblTransactionCostExpectation,
				dblTransactionCostVariance, dblCharacteristicTime, dblExecutionTimeUpperBound,
					dblHyperboloidBoundaryValue, r1ToR1Holdings, r1ToR1TradeRate);
		} catch (java.lang.Exception e) {
			e.printStackTrace();
		}

		return null;
	}

	/**
	 * Almgren2003PowerImpactContinuous Constructor
	 * 
	 * @param dblExecutionTime The Execution Time
	 * @param dblTransactionCostExpectation The Expected Transaction Cost
	 * @param dblTransactionCostVariance The Variance of the Transaction Cost
	 * @param dblCharacteristicTime The Optimal Trajectory's "Characteristic" Time
	 * @param dblExecutionTimeUpperBound The Optimal Trajectory's Execution Time Upper Bound (if it exists)
	 * @param dblHyperboloidBoundaryValue The Hyperboloid Boundary Value
	 * @param r1ToR1Holdings The Optimal Trajectory R^1 To R^1 Holdings Function
	 * @param r1ToR1TradeRate The Optimal Trajectory R^1 To R^1 Trade Rate Function
	 * 
	 * @throws java.lang.Exception Thrown if the Inputs are Invalid
	 */

	public Almgren2003PowerImpactContinuous (
		final double dblExecutionTime,
		final double dblTransactionCostExpectation,
		final double dblTransactionCostVariance,
		final double dblCharacteristicTime,
		final double dblExecutionTimeUpperBound,
		final double dblHyperboloidBoundaryValue,
		final org.drip.function.definition.R1ToR1 r1ToR1Holdings,
		final org.drip.function.definition.R1ToR1 r1ToR1TradeRate)
		throws java.lang.Exception
	{
		super (dblExecutionTime, dblTransactionCostExpectation, dblTransactionCostVariance,
			dblCharacteristicTime, r1ToR1Holdings, r1ToR1TradeRate);

		if (!org.drip.quant.common.NumberUtil.IsValid (_dblHyperboloidBoundaryValue =
			dblHyperboloidBoundaryValue))
			throw new java.lang.Exception ("Almgren2003PowerImpactContinuous Constructor => Invalid Inputs");

		_dblExecutionTimeUpperBound = dblExecutionTimeUpperBound;
	}

	/**
	 * Retrieve the Optimal Trajectory Execution Time Upper Bound (if it exists)
	 * 
	 * @return The Optimal Trajectory Execution Time Upper Bound (if it exists)
	 */

	public double executionTimeUpperBound()
	{
		return _dblExecutionTimeUpperBound;
	}

	/**
	 * Retrieve the Optimal Trajectory Hyperboloid Boundary Value
	 * 
	 * @return The Optimal Trajectory Hyperboloid Boundary Value
	 */

	public double hyperboloidBoundaryValue()
	{
		return _dblHyperboloidBoundaryValue;
	}
}
