
package org.drip.execution.optimum;

/*
 * -*- mode: java; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*-
 */

/*!
 * Copyright (C) 2016 Lakshmi Krishnamurthy
 * 
 *  This file is part of DRIP, a free-software/open-source library for fixed income analysts and developers -
 * 		http://www.credit-trader.org/Begin.html
 * 
 *  DRIP is a free, full featured, fixed income rates, credit, and FX analytics library with a focus towards
 *  	pricing/valuation, risk, and market making.
 * 
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *   	you may not use this file except in compliance with the License.
 *   
 *  You may obtain a copy of the License at
 *  	http://www.apache.org/licenses/LICENSE-2.0
 *  
 *  Unless required by applicable law or agreed to in writing, software
 *  	distributed under the License is distributed on an "AS IS" BASIS,
 *  	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  
 *  See the License for the specific language governing permissions and
 *  	limitations under the License.
 */

/**
 * LinearTradingEnhancedTrajectory contains the Trading Trajectory generated by one of the Methods outlined
 *  in the Almgren (2003) Scheme for Continuous Trading Approximation for Linear Trading Enhanced Temporary
 *  Impact Volatility. The References are:
 * 
 * 	- Almgren, R., and N. Chriss (1999): Value under Liquidation, Risk 12 (12).
 * 
 * 	- Almgren, R., and N. Chriss (2000): Optimal Execution of Portfolio Transactions, Journal of Risk 3 (2)
 * 		5-39.
 * 
 * 	- Almgren, R. (2003): Optimal Execution with Nonlinear Impact Functions and Trading-Enhanced Risk,
 * 		Applied Mathematical Finance 10 (1) 1-18.
 * 
 * 	- Almgren, R., and N. Chriss (2003): Bidding Principles, Risk 97-102.
 * 
 * 	- Bertsimas, D., and A. W. Lo (1998): Optimal Control of Execution Costs, Journal of Financial Markets,
 * 		1, 1-50.
 * 
 * @author Lakshmi Krishnamurthy
 */

public class LinearTradingEnhancedTrajectory extends
	org.drip.execution.optimum.EfficientDiscreteTradingTrajectory {
	private double _dblCharacteristicSize = java.lang.Double.NaN;
	private double _dblCharacteristicTime = java.lang.Double.NaN;

	/**
	 * Construct a Standard LinearTradingEnhancedTrajectory Instance
	 * 
	 * @param dtt The Trading Trajectory
	 * @param apep The Arithmetic Price Walk Evolution Parameters
	 * @param dblCharacteristicTime The Optimal Trajectory's "Characteristic" Time
	 * @param dblCharacteristicSize The Optimal Trajectory's "Characteristic" Size
	 * 
	 * @return The LinearTradingEnhancedTrajectory Instance
	 */

	public static LinearTradingEnhancedTrajectory Standard (
		final org.drip.execution.strategy.DiscreteTradingTrajectory dtt,
		final org.drip.execution.dynamics.ArithmeticPriceEvolutionParameters apep,
		final double dblCharacteristicTime,
		final double dblCharacteristicSize)
	{
		if (null == dtt) return null;

		try {
			org.drip.measure.gaussian.R1UnivariateNormal r1un = (new
				org.drip.execution.capture.TrajectoryShortfallEstimator (dtt)).totalCostDistributionSynopsis
					(apep);

			return null == r1un ? null : new LinearTradingEnhancedTrajectory (dtt.executionTimeNode(),
				dtt.holdings(), dtt.tradeList(), r1un.mean(), r1un.variance(), dblCharacteristicTime,
					dblCharacteristicSize);
		} catch (java.lang.Exception e) {
			e.printStackTrace();
		}

		return null;
	}

	/**
	 * LinearTradingEnhancedTrajectory Constructor
	 * 
	 * @param adblExecutionTimeNode Array containing the Trajectory Time Nodes
	 * @param adblHoldings Array containing the Holdings
	 * @param adblTradeList Array containing the Trade List
	 * @param dblTransactionCostExpectation The Expected Transaction Cost
	 * @param dblTransactionCostVariance The Variance of the Transaction Cost
	 * @param dblCharacteristicTime The Optimal Trajectory's "Characteristic" Time
	 * @param dblCharacteristicSize The Optimal Trajectory's "Characteristic" Size
	 * 
	 * @throws java.lang.Exception Thrown if the Inputs are Invalid
	 */

	public LinearTradingEnhancedTrajectory (
		final double[] adblExecutionTimeNode,
		final double[] adblHoldings,
		final double[] adblTradeList,
		final double dblTransactionCostExpectation,
		final double dblTransactionCostVariance,
		final double dblCharacteristicTime,
		final double dblCharacteristicSize)
		throws java.lang.Exception
	{
		super (adblExecutionTimeNode, adblHoldings, adblTradeList, dblTransactionCostExpectation,
			dblTransactionCostVariance);

		if (!org.drip.quant.common.NumberUtil.IsValid (_dblCharacteristicTime = dblCharacteristicTime) ||
			!org.drip.quant.common.NumberUtil.IsValid (_dblCharacteristicSize = dblCharacteristicSize))
			throw new java.lang.Exception ("LinearTradingEnhancedTrajectory Constructor => Invalid Inputs");
	}

	/**
	 * Retrieve the Optimal Trajectory Characteristic Size
	 * 
	 * @return The Optimal Trajectory Characteristic Size
	 */

	public double characteristicSize()
	{
		return _dblCharacteristicSize;
	}

	/**
	 * Retrieve the Optimal Trajectory Characteristic Time
	 * 
	 * @return The Optimal Trajectory Characteristic Time
	 */

	public double characteristicTime()
	{
		return _dblCharacteristicTime;
	}
}
